/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import jpa.AgendamentoJpaController;
import jpa.CirurgiaMaterialJpaController;
import jpa.CirurgiaMedicamentoJpaController;
import jpa.PacienteJpaController;
import model.Agendamento;
import model.CirurgiaMaterial;
import model.CirurgiaMedicamento;
import model.Material;
import model.Medicamento;
import model.Paciente;

/**
 *
 * @author Christopher
 */
public class guiCirurgiaMaterial extends javax.swing.JInternalFrame {

    /**
     * Creates new form guiCirurgiaMaterial
     */
    Paciente paciente;
    Agendamento ag;

    public guiCirurgiaMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPaciente = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtPront = new javax.swing.JTextField();
        burcarAgend = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataCirurgia = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtCirurgia = new javax.swing.JTextField();
        cboMateriais = new javax.swing.JComboBox();
        txtPeriodo = new javax.swing.JTextField();
        bntAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMaterials = new javax.swing.JList();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lstPaciente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPacienteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPaciente);

        jLabel1.setText("Prontuário:");

        txtPront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProntActionPerformed(evt);
            }
        });

        burcarAgend.setText("Buscar agendamento");
        burcarAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burcarAgendActionPerformed(evt);
            }
        });

        txtNome.setEditable(false);

        jLabel6.setText("Cirurgias do Paciente:");

        jLabel2.setText("Data da Cirurgia:");

        txtDataCirurgia.setEnabled(false);

        jLabel16.setText("Materiais para Cirurgia:");

        txtCirurgia.setEditable(false);

        bntAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Adicionar.jpg"))); // NOI18N
        bntAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstMaterials);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(burcarAgend, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel2))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(135, 135, 135))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(burcarAgend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel16)
                    .addGap(26, 26, 26)
                    .addComponent(cboMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPacienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPacienteValueChanged
        // TODO add your handling code here:

        Agendamento a = (Agendamento) lstPaciente.getSelectedValue();

        txtPront.setText(a.getPaciente().getId().toString());
        txtNome.setText(a.getPaciente().getNome().toString());
        txtDataCirurgia.setDate(a.getDataInicio().getTime());
        txtCirurgia.setText(a.getProcedimento().toString());

        lstMaterials.removeAll();
        List l = new CirurgiaMedicamentoJpaController().getMedicamentos(a.getId().toString());
        lstMaterials.setListData(l.toArray());
    }//GEN-LAST:event_lstPacienteValueChanged

    private void txtProntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProntActionPerformed

    private void burcarAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burcarAgendActionPerformed
        // TODO add your handling code here:
        paciente = new PacienteJpaController().getPaciente(txtPront.getText());

        txtNome.setText(paciente.getNome().toString());

        try {
            List l = new AgendamentoJpaController().getAgendamentoPac(txtPront.getText());
            lstPaciente.setListData(l.toArray());

            if (l.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não foi agendada Cirurgia com este número de prontuário");
                txtNome.setText("");
                txtPront.setText("");
                txtDataCirurgia.setDate(null);
                txtCirurgia.setText("");
                lstPaciente.setModel(new DefaultListModel());
                lstMaterials.setModel(new DefaultListModel());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi agendada Cirurgia com este número de prontuário");
            txtNome.setText("");
            txtPront.setText("");
            txtDataCirurgia.setDate(null);
            txtCirurgia.setText("");
            lstPaciente.setModel(new DefaultListModel());
            lstMaterials.setModel(new DefaultListModel());
        }
    }//GEN-LAST:event_burcarAgendActionPerformed

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed

        CirurgiaMaterial cm = new CirurgiaMaterial();
        ag = (Agendamento) lstPaciente.getSelectedValue();

        cm.setAgendamento(ag);
        cm.setDataCirurgia(txtDataCirurgia.getCalendar());
        cm.setMaterial((Material) cboMateriais.getSelectedItem());
        cm.setPeriodo(txtPeriodo.getText());

        new CirurgiaMaterialJpaController().create(cm);
        JOptionPane.showMessageDialog(null, "Novo material adicionado a Cirurgia '" + ag.getProcedimento() + "'\nPaciente: " + ag.getPaciente().getNome().toString());
        lstMaterials.removeAll();
        List l = new CirurgiaMaterialJpaController().getMaterial(ag.getId().toString());
        lstMaterials.setListData(l.toArray());
        //lstMedicamento.setModel(new DefaultListModel());
    }//GEN-LAST:event_bntAdicionarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton burcarAgend;
    private javax.swing.JComboBox cboMateriais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstMaterials;
    private javax.swing.JList lstPaciente;
    private javax.swing.JTextField txtCirurgia;
    private com.toedter.calendar.JDateChooser txtDataCirurgia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeriodo;
    private javax.swing.JTextField txtPront;
    // End of variables declaration//GEN-END:variables
}
